# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Check Rust
on:
  push:
    branches: ["main", "v*"]
    # Also run on tag pushes, as the release.yml doesn't currently run tests
    tags: ["v*"]
    paths-ignore:
      - ".plugin-manifests/**"
      - "*.md"
      - "LICENSE"
      - ".github/workflow/audits.yml"
      - "supply-chain/**"
  pull_request:
    branches: ["main", "v*"]
    paths-ignore:
      - ".plugin-manifests/**"
      - "*.md"
      - "LICENSE"
      - ".github/workflow/audits.yml"
      - "supply-chain/**"

env:
  CARGO_TERM_COLOR: always
jobs:
  lint-rust:
    name: Lint Rust
    runs-on: "ubuntu-latest"
    steps:
      # install dependencies
      - name: Install latest Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.68'
          default: true
          components: clippy, rustfmt
      - name: "Install Wasm Rust target"
        run: rustup target add wasm32-wasi && rustup target add wasm32-unknown-unknown
        shell: bash
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "${{ runner.os }}-full-${{ hashFiles('./Cargo.lock') }}"

      - uses: actions/checkout@v3

      - name: Lint
        run: make lint

  build-rust:
    name: Build Cloud Plugin
    runs-on: ${{ matrix.os }}
    needs: [lint-rust]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      # install dependencies
      - name: Install latest Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.68'
          default: true
          components: clippy, rustfmt
      - name: "Install Wasm Rust target"
        run: rustup target add wasm32-wasi && rustup target add wasm32-unknown-unknown
        shell: bash
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "${{ runner.os }}-full-${{ hashFiles('./Cargo.lock') }}"

      - uses: actions/checkout@v3

      - name: Build
        run: make build
        env:
          CARGO_INCREMENTAL: 0

  test-rust:
    name: Plugin Unit Tests
    runs-on: ${{ matrix.os }}
    needs: [lint-rust]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:

      # install dependencies
      - name: Install latest Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.68'
          default: true
          components: clippy, rustfmt
      - name: "Install Wasm Rust target"
        run: rustup target add wasm32-wasi && rustup target add wasm32-unknown-unknown
        shell: bash
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "${{ runner.os }}-full-${{ hashFiles('./Cargo.lock') }}"

      - uses: actions/checkout@v3
      
      - name: Run Tests
        run: make test
        env:
          CARGO_INCREMENTAL: 0
          RUST_LOG: trace