name: deploy fermyon.com preview
on:
  workflow_dispatch: {}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
    - uses: actions/checkout@v3

    - name: Install latest Rust stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: "1.68"
        default: true
        components: clippy, rustfmt

    - name: "Install Wasm Rust target"
      run: rustup target add wasm32-wasi && rustup target add wasm32-unknown-unknown
      shell: bash

    - name: "build plugin"
      run: cargo build --release
      shell: bash

    - name: Setup `spin`
      uses: fermyon/actions/spin/setup@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: create tar file
      run:|
        cp target/release/cloud-plugin cloud
        tar -cvf cloud.tar.gz cloud
        cp cloud.tar.gz spin-app/assets/

    - name: create tar file
      run:|
        cp target/release/cloud-plugin cloud
        tar -cvf cloud.tar.gz cloud
        cp cloud.tar.gz spin-app/assets/


    - name: build and deploy preview
      uses: fermyon/actions/spin/deploy@v1
      with:
        fermyon_token: ${{ secrets.FERMYON_CLOUD_TOKEN }}

    # - name: enable PREVIEW_MODE
    #   run: |
    #     sed -i 's/PREVIEW_MODE = "0"/PREVIEW_MODE = "1"/g' spin.toml